name: Deploy connorbray.net

on:
  push:
    branches:
      - main
    paths:
      - 'sites/main/**'
      - 'packages/**'
      - 'services/**'

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: v1.2.10

      - name: Install dependencies
        run: bun install --no-cache

      - uses: nrwl/nx-set-shas@v4

      - name: Build and deploy Cloudflare Worker
        run: npx nx deploy site
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}


