# name: Deploy connorbray.net preview

# env:
#   NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

# on:
#   pull_request:
#     branches:
#       - main

# permissions:
#   actions: read
#   contents: read

# jobs:
#   main:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           filter: tree:0
#           fetch-depth: 0
      
#       - uses: oven-sh/setup-bun@v1
#         with:
#           bun-version: v1.2.10

#       - run: bun install --no-cache
#       - uses: nrwl/nx-set-shas@v4

